# Generated by Django 5.1.2 on 2024-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeAddictionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ngo_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('bed_capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
